### ISSUE TITLE
User friendly formatter

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/goci#1261]
User story:
As a user who wants to format my GWAS analysis output into a ready-to-submit format to the GWAS catalog, I want to click several buttons to get the result downloaded and ready to submit.

User scenarios:
|                                                                                          | Occasional Users (external users)                                        | Occasional Users (external users)                                           | Frequent users (Internal users)   |
| ---------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ | --------------------------------------------------------------------------- | --------------------------------- |
| Number of publications needed to handle (number of configure files need to be generated) | 1                                                                        | 1                                                                           | \>1                               |
| Number of files need to handle                                                           | Single file (or less than 5 files)                                       | Batch files                                                                 | Batch files                       |
| Generate the configure file                                                              | Web assembly (generate, edit and apply configure files) - 4GB limitation | Web assembly                                                                | Terminal (Need instruction)       |
| Edit the configure file                                                                  | Web assembly                                                             | Web assembly                                                                | VScode / micro (Need instruction) |
| Apply the configure file to sumstats                                                     | Web assembly                                                             | Terminal (support local running, PBS, LSF,slurm)- needs a clear instruction | Terminal (Need instruction)       |

To-do list:
* Python code
- [ ] Integrate sum-stats-formatter into gwas-sumstats-tools (!)
- [ ] Improve the speed of validation  (maybe)
* Webassembly
- [x] A simple demo only contains the validation function from gwas-sumstats-tools
- [ ] Active the function of generating configure file in formatted
- [ ] Active the function of applying a configure to the input
- [ ] Allow the user to edit the configure in the text box and apply the configure file to the input file
