### ISSUE TITLE
Release depocuration admin features V3 and fully enable curation workflow

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1364]
- [x] Release & test event tracking feature in sandbox @sajo-ebi & curators see gwas-curation-ui#137 
- [x] Fix bug with bulk trait upload in sandbox @sajo-ebi see goci#1354
- [x] Test import end to end in sandbox (Curators)
- [x] Set date for release (all)
- [x] Run database copy script @sajo-ebi , see gwas-curation-service#197
- [x] Releaase analysis software feature in the gwas-sumstats-services @karatugo 
- [x] Release all admin features in production @sajo-ebi @ala-ebi 
- [x] Test admin features in production, including end to end testing with one new publication, including creation, curation, status changes and import (Curators)
- [x] Upload the old curation file metadata to the Production Mongodb database @sprintell 

See also detailed plan here: https://docs.google.com/document/d/1LRUdklIrJ5A-ZW2mK8xdZdCtOAZehWAhYdGWUe1xArA/edit?usp=sharing
